# Generated by Django 6.1.1 on 2026-09-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('starpay', 'ستارپی')], max_length=50, unique=True, verbose_name='نام درگاه')),
                ('merchant_id', models.CharField(max_length=200, verbose_name='Merchant ID')),
                ('api_key', models.CharField(max_length=200, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('callback_url', models.URLField(verbose_name='URL بازگشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیم درگاه پرداخت',
                'verbose_name_plural': 'تنظیمات درگاه\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50, verbose_name='درگاه پرداخت')),
                ('reference_id', models.CharField(max_length=200, unique=True, verbose_name='شماره ارجاع درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'درحال انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='روش پرداخت')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ درگاه')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='شماره تلفن مشتری')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_3a2ee8_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx')],
            },
        ),
    ]
