# Generated by Django 6.1.1 on 2026-09-12 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصد'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار تخفیف')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='حداکثر تخفیف (تومان)')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='حداقل مبلغ سفارش')),
                ('max_usage_per_customer', models.IntegerField(default=1, verbose_name='حداکثر استفاده برای هر مشتری')),
                ('max_total_usage', models.IntegerField(blank=True, null=True, verbose_name='حداکثر کل استفاده')),
                ('current_usage', models.IntegerField(default=0, verbose_name='استفاده\u200cهای فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن میهمان')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='شماره سفارش')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار تخفیف')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='discounts.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت استفاده کد تخفیف',
                'verbose_name_plural': 'ثبت استفاده کدهای تخفیف',
                'ordering': ['-used_at'],
            },
        ),
    ]
