# Generated by Django 6.1.1 on 2026-09-12 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(unique=True, verbose_name='نام اختصاری')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('icon', models.ImageField(upload_to='categories/', verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='menu_catego_is_acti_0ce834_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='شماره میز')),
                ('qr_code', models.CharField(max_length=500, unique=True, verbose_name='کد QR')),
                ('capacity', models.IntegerField(default=4, verbose_name='ظرفیت نفری')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='محل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میز\u200cها',
                'ordering': ['table_number'],
                'indexes': [models.Index(fields=['is_active'], name='menu_table_is_acti_dae3f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('image', models.ImageField(upload_to='menu_items/', verbose_name='تصویر')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='menu_menuit_categor_792b2d_idx'), models.Index(fields=['is_available'], name='menu_menuit_is_avai_3a30d9_idx')],
            },
        ),
    ]
