# Generated by Django 6.1.1 on 2026-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='p_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام فارسی دسته'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='مواد تشکیل\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='محبوب'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='p_description',
            field=models.TextField(blank=True, verbose_name='توضیح فارسی'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='p_ingredients',
            field=models.TextField(blank=True, verbose_name='مواد تشکیل\u200cدهنده فارسی'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='p_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام فارسی'),
        ),
    ]
