# Generated by Django 6.1.1 on 2026-09-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'درحال انتظار'), ('confirmed', 'تایید شده'), ('preparing', 'درحال تهیه'), ('ready', 'آماده'), ('served', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('refunded', 'بازگردانده شده')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کل مبلغ')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='تخفیف')),
                ('discount_code_id', models.IntegerField(blank=True, null=True, verbose_name='کد تخفیف ID')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مالیات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('guest_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.guestcustomer', verbose_name='مشتری میهمان')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.table', verbose_name='میز')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cشده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت واحد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت خاص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem', verbose_name='محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('method', models.CharField(choices=[('card', 'کارت بانکی'), ('wallet', 'کیف پول'), ('cash', 'نقد')], max_length=20, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=200, unique=True, verbose_name='شماره تراکنش')),
                ('is_successful', models.BooleanField(default=False, verbose_name='موفق')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table', '-created_at'], name='orders_orde_table_i_090818_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
    ]
