# Generated by Django 6.1.1 on 2026-09-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=30, unique=True, verbose_name='نوع یادآوری')),
                ('sms_template', models.TextField(verbose_name='قالب پیامک')),
                ('email_subject', models.CharField(max_length=200, verbose_name='عنوان ایمیل')),
                ('email_template', models.TextField(verbose_name='قالب ایمیل')),
                ('description', models.TextField(blank=True, verbose_name='توضیح متغیرها (مثلا {order_id}, {customer_name})')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب یادآوری',
                'verbose_name_plural': 'قالب\u200cهای یادآوری',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'سفارش تایید شده'), ('order_preparing', 'سفارش درحال تهیه'), ('order_ready', 'سفارش آماده'), ('order_served', 'سفارش تحویل داده شد'), ('payment_received', 'پرداخت دریافت شد'), ('order_cancelled', 'سفارش لغو شد')], max_length=30, verbose_name='نوع یادآوری')),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل'), ('in_app', 'درون\u200cبرنامه')], max_length=20, verbose_name='کانال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن یادآوری')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('send_attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ارسال')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تلاش')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.guestcustomer', verbose_name='مشتری میهمان')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cشده')),
            ],
            options={
                'verbose_name': 'یادآوری',
                'verbose_name_plural': 'یادآوری\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_sent', 'created_at'], name='notificatio_is_sent_2262e4_idx'), models.Index(fields=['order'], name='notificatio_order_i_0e31eb_idx')],
            },
        ),
    ]
